- KeyItemProvince                   重点项目
- KeyItemProvinceAudit              重点项目审核
- KeyItemProvinceDeclareSummary     重点项目申报汇总
- KeyItemProvinceReview             重点项目评审
- KeyItemProvinceSchedule           重点项目调度
- KeyItemProvinceScheduleAudit      重点项目调度审核